export default {
  STATE_BEER : "STATE_BEER",
  STATE_HEART : "STATE_HEART",
  STATE_SMOKE: "STATE_SMOKE",
  STATE_CHICKEN: "STATE_CHICKEN",
  STATE_PUKE: "STATE_PUKE",
  NOT_CONNECTED: "NOT_CONNECTED"
}
