export default {
  STATE_BEER : "STATE_BEER",
  STATE_LOVE : "STATE_LOVE",
  STATE_SMOKE: "STATE_SMOKE",
  STATE_FOOD: "STATE_FOOD",
  STATE_COCKTAIL: "STATE_COCKTAIL",
  STATE_PUKE: "STATE_PUKE",
  NOT_CONNECTED: "NOT_CONNECTED"
}
